# **FEATURE SCALING**

In [ ]:
import pandas as pd
import numpy as np
import scipy as stats

df=pd.read_csv('/content/bmi.csv')
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [ ]:
df.dropna()
max_vals=np.max(np.abs(df[['Height','Weight']]))
max_vals

199

In [ ]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
df[['Height','Weight']]=sc.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.247939 -0.309117      4
1      Male  1.164872 -0.587322      2
2    Female  0.920357  0.123647      4
3    Female  1.531645 -0.061823      3
4      Male -1.280283 -1.391027      3
..      ...       ...       ...    ...
495  Female -1.219155  1.452850      5
496  Female  0.859228  0.463676      4
497  Female -1.769315  0.927351      5
498    Male -1.219155 -0.340029      5
499    Male  0.186810  0.772793      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.576271  0.418182      4
1      Male  0.830508  0.336364      2
2    Female  0.762712  0.545455      4
3    Female  0.932203  0.490909      3
4      Male  0.152542  0.100000      3
..      ...       ...       ...    ...
495  Female  0.169492  0.936364      5
496  Female  0.745763  0.645455      4
497  Female  0.016949  0.781818      5
498    Male  0.169492  0.409091      5
499    Male  0.559322  0.736364      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.809353  0.587322      4
1      Male  0.926867  0.375390      2
2    Female  0.813400  0.581704      4
3    Female  0.884810  0.465951      3
4      Male  0.836314  0.548250      3
..      ...       ...       ...    ...
495  Female  0.178116  0.984010      5
496  Female  0.756127  0.654425      4
497  Female  0.021674  0.999765      5
498    Male  0.382762  0.923847      5
499    Male  0.604868  0.796326      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
scaler=MaxAbsScaler()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.809353  0.587322      4
1      Male  0.926867  0.375390      2
2    Female  0.813400  0.581704      4
3    Female  0.884810  0.465951      3
4      Male  0.836314  0.548250      3
..      ...       ...       ...    ...
495  Female  0.178116  0.984010      5
496  Female  0.756127  0.654425      4
497  Female  0.021674  0.999765      5
498    Male  0.382762  0.923847      5
499    Male  0.604868  0.796326      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.230958 -0.274051      4
1      Male  0.505746 -0.773495      2
2    Female  0.240421 -0.287290      4
3    Female  0.407403 -0.560076      3
4      Male  0.294002 -0.366128      3
..      ...       ...       ...    ...
495  Female -1.245095  0.660788      5
496  Female  0.106496 -0.115916      4
497  Female -1.610911  0.697918      5
498    Male -0.766562  0.519009      5
499    Male -0.247201  0.218490      5

[500 rows x 4 columns]

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
data=pd.read_csv('/content/income(1) (1).csv',na_values=[" ?"])
data

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
0,45,Private,HS-grad,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,28,United-States,"less than or equal to 50,000"
1,24,Federal-gov,HS-grad,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"
2,44,Private,Some-college,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,"greater than 50,000"
3,27,Private,9th,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,"less than or equal to 50,000"
4,20,Private,Some-college,Never-married,Sales,Not-in-family,White,Male,0,0,35,United-States,"less than or equal to 50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,Local-gov,HS-grad,Never-married,Farming-fishing,Not-in-family,Black,Male,594,0,60,United-States,"less than or equal to 50,000"
31974,34,Local-gov,Some-college,Never-married,Protective-serv,Not-in-family,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31975,23,Private,Some-college,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,"less than or equal to 50,000"
31976,42,Local-gov,Some-college,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31977,29,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,"less than or equal to 50,000"

In [ ]:
data.isnull().sum()

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

In [ ]:
missing=data[data.isnull().any(axis=1)]
missing

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
8,17,NaN,11th,Never-married,NaN,Own-child,White,Female,0,0,5,United-States,"less than or equal to 50,000"
17,32,NaN,Some-college,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,United-States,"less than or equal to 50,000"
29,22,NaN,Some-college,Never-married,NaN,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"
42,52,NaN,12th,Never-married,NaN,Other-relative,Black,Male,594,0,40,United-States,"less than or equal to 50,000"
44,63,NaN,1st-4th,Married-civ-spouse,NaN,Husband,White,Male,0,0,35,United-States,"less than or equal to 50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31892,59,NaN,Bachelors,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,United-States,"greater than 50,000"
31934,20,NaN,HS-grad,Never-married,NaN,Other-relative,White,Female,0,0,35,United-States,"less than or equal to 50,000"
31945,28,NaN,Some-college,Married-civ-spouse,NaN,Wife,White,Female,0,1887,40,United-States,"greater than 50,000"
31967,80,NaN,HS-grad,Widowed,NaN,Not-in-family,White,Male,0,0,24,United-States,"less than or equal to 50,000"
31968,17,NaN,11th,Never-married,NaN,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"

In [ ]:
data2 = data.dropna(axis=0)
data2

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
0,45,Private,HS-grad,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,28,United-States,"less than or equal to 50,000"
1,24,Federal-gov,HS-grad,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"
2,44,Private,Some-college,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,"greater than 50,000"
3,27,Private,9th,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,"less than or equal to 50,000"
4,20,Private,Some-college,Never-married,Sales,Not-in-family,White,Male,0,0,35,United-States,"less than or equal to 50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,Local-gov,HS-grad,Never-married,Farming-fishing,Not-in-family,Black,Male,594,0,60,United-States,"less than or equal to 50,000"
31974,34,Local-gov,Some-college,Never-married,Protective-serv,Not-in-family,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31975,23,Private,Some-college,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,"less than or equal to 50,000"
31976,42,Local-gov,Some-college,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31977,29,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,"less than or equal to 50,000"

In [ ]:
sal=data['SalStat']
data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})
print(data2['SalStat'])

0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64

/tmp/ipykernel_443/2010331391.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})

In [ ]:
sal2=data2['SalStat']
dfs=pd.concat([sal,sal2],axis=1)
dfs

                             SalStat  SalStat
0       less than or equal to 50,000      0.0
1       less than or equal to 50,000      0.0
2                greater than 50,000      1.0
3       less than or equal to 50,000      0.0
4       less than or equal to 50,000      0.0
...                              ...      ...
31973   less than or equal to 50,000      0.0
31974   less than or equal to 50,000      0.0
31975   less than or equal to 50,000      0.0
31976   less than or equal to 50,000      0.0
31977   less than or equal to 50,000      0.0

[31978 rows x 2 columns]

In [ ]:
data2

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
0,45,Private,HS-grad,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,28,United-States,0
1,24,Federal-gov,HS-grad,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,0
2,44,Private,Some-college,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,1
3,27,Private,9th,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,0
4,20,Private,Some-college,Never-married,Sales,Not-in-family,White,Male,0,0,35,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,Local-gov,HS-grad,Never-married,Farming-fishing,Not-in-family,Black,Male,594,0,60,United-States,0
31974,34,Local-gov,Some-college,Never-married,Protective-serv,Not-in-family,White,Female,0,0,40,United-States,0
31975,23,Private,Some-college,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,0
31976,42,Local-gov,Some-college,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,0
31977,29,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,0

In [ ]:
new_data=pd.get_dummies(data2, drop_first=True)
new_data

,age,capitalgain,capitalloss,hoursperweek,SalStat,JobType_ Local-gov,JobType_ Private,JobType_ Self-emp-inc,JobType_ Self-emp-not-inc,JobType_ State-gov,...,nativecountry_ Portugal,nativecountry_ Puerto-Rico,nativecountry_ Scotland,nativecountry_ South,nativecountry_ Taiwan,nativecountry_ Thailand,nativecountry_ Trinadad&Tobago,nativecountry_ United-States,nativecountry_ Vietnam,nativecountry_ Yugoslavia
0,45,0,0,28,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,24,0,0,40,0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,44,0,0,40,1,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,27,0,0,40,0,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,20,0,0,35,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,594,0,60,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31974,34,0,0,40,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31975,23,0,0,40,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31976,42,0,0,40,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31977,29,0,0,40,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
columns_list=list(new_data.columns)

features=list(set(columns_list)-set(['SalStat']))
print(features)

y=new_data['SalStat'].values
print(y)

['JobType_ Without-pay', 'nativecountry_ Poland', 'race_ Other', 'EdType_ HS-grad', 'nativecountry_ Philippines', 'occupation_ Protective-serv', 'hoursperweek', 'occupation_ Prof-specialty', 'relationship_ Unmarried', 'JobType_ Local-gov', 'nativecountry_ Portugal', 'nativecountry_ Thailand', 'relationship_ Wife', 'EdType_ 7th-8th', 'EdType_ 11th', 'JobType_ State-gov', 'nativecountry_ Laos', 'nativecountry_ India', 'EdType_ Masters', 'nativecountry_ Dominican-Republic', 'nativecountry_ Greece', 'nativecountry_ China', 'nativecountry_ United-States', 'JobType_ Private', 'nativecountry_ Honduras', 'nativecountry_ Germany', 'JobType_ Self-emp-not-inc', 'nativecountry_ Hungary', 'nativecountry_ Hong', 'occupation_ Craft-repair', 'JobType_ Self-emp-inc', 'EdType_ 9th', 'EdType_ Prof-school', 'EdType_ Assoc-voc', 'nativecountry_ Japan', 'nativecountry_ El-Salvador', 'maritalstatus_ Married-AF-spouse', 'nativecountry_ Italy', 'occupation_ Exec-managerial', 'nativecountry_ Haiti', 'nativecountry_ Scotland', 'occupation_ Sales', 'EdType_ Some-college', 'relationship_ Not-in-family', 'occupation_ Armed-Forces', 'nativecountry_ Puerto-Rico', 'maritalstatus_ Widowed', 'EdType_ Doctorate', 'EdType_ Bachelors', 'race_ White', 'EdType_ Assoc-acdm', 'occupation_ Handlers-cleaners', 'nativecountry_ Guatemala', 'maritalstatus_ Never-married', 'nativecountry_ Cuba', 'occupation_ Machine-op-inspct', 'nativecountry_ Trinadad&Tobago', 'nativecountry_ Ecuador', 'nativecountry_ Yugoslavia', 'nativecountry_ Taiwan', 'occupation_ Transport-moving', 'EdType_ 5th-6th', 'EdType_ 12th', 'occupation_ Priv-house-serv', 'nativecountry_ Canada', 'race_ Asian-Pac-Islander', 'maritalstatus_ Separated', 'maritalstatus_ Married-civ-spouse', 'nativecountry_ France', 'nativecountry_ Nicaragua', 'nativecountry_ Mexico', 'occupation_ Tech-support', 'occupation_ Other-service', 'capitalgain', 'race_ Black', 'nativecountry_ Jamaica', 'age', 'nativecountry_ Vietnam', 'occupation_ Farming-fishing', 'nativecountry_ Ireland', 'EdType_ Preschool', 'nativecountry_ England', 'relationship_ Own-child', 'gender_ Male', 'nativecountry_ South', 'nativecountry_ Iran', 'nativecountry_ Peru', 'nativecountry_ Holand-Netherlands', 'maritalstatus_ Married-spouse-absent', 'capitalloss', 'relationship_ Other-relative', 'nativecountry_ Columbia', 'nativecountry_ Outlying-US(Guam-USVI-etc)', 'EdType_ 1st-4th']
[0 0 1 ... 0 0 0]

In [ ]:
x = new_data[features].values
print(x)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]

In [ ]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.3, random_state=0)
KNN_classifier=KNeighborsClassifier(n_neighbors = 5)
KNN_classifier.fit(train_x,train_y)

KNeighborsClassifier()

In [ ]:
prediction = KNN_classifier.predict(test_x)
confusionMmatrix = confusion_matrix(test_y, prediction)
print(confusionMmatrix)

[[6176  647]
 [ 808 1418]]

In [ ]:
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(test_y, prediction)
print(acc_score)

0.8392087523483258

In [ ]:
print('Misclassified samples: %d' % (test_y != prediction).sum())

Misclassified samples: 1455

In [ ]:
data.shape

(31978, 13)

# **FEATURE SELECTION TECHNIQUES**

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
import seaborn as sns
tips=sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
contingency_table=pd.crosstab(tips['sex'],tips['time'])
print(contingency_table)

time    Lunch  Dinner
sex
Male       33     124
Female     35      52

In [ ]:
chi2, p, _, _ = chi2_contingency(contingency_table)
print(f"Chi-Square Statistic: {chi2}")
print(f"P-value: {p}")

Chi-Square Statistic: 9.343808982970623
P-value: 0.002237400118075248

In [ ]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, mutual_info_classif, f_classif
data={
    'Feature1':[1,2,3,4,5],
    'Feature2': ['A','B','C','A','B'],
    'Feature3':[0,1,1,0,1],
    'Target' :[0,1,1,0,1]
}

df=pd.DataFrame(data)
X=df[['Feature1','Feature3']]
y=df['Target']

selector=SelectKBest(score_func=mutual_info_classif, k=1)
X_new = selector.fit_transform (X,y)
selected_feature_indices = selector.get_support(indices=True)
selected_features = X.columns[selected_feature_indices]
print("Selected Features:")
print(selected_features)

Selected Features:
Index(['Feature3'], dtype='object')

# **FEATURE SCALING**

In [ ]:
import pandas as pd
import numpy as np
import scipy as stats

df=pd.read_csv('/content/bmi.csv')
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [ ]:
df.dropna()
max_vals=np.max(np.abs(df[['Height','Weight']]))
max_vals

199

In [ ]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
df[['Height','Weight']]=sc.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.247939 -0.309117      4
1      Male  1.164872 -0.587322      2
2    Female  0.920357  0.123647      4
3    Female  1.531645 -0.061823      3
4      Male -1.280283 -1.391027      3
..      ...       ...       ...    ...
495  Female -1.219155  1.452850      5
496  Female  0.859228  0.463676      4
497  Female -1.769315  0.927351      5
498    Male -1.219155 -0.340029      5
499    Male  0.186810  0.772793      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.576271  0.418182      4
1      Male  0.830508  0.336364      2
2    Female  0.762712  0.545455      4
3    Female  0.932203  0.490909      3
4      Male  0.152542  0.100000      3
..      ...       ...       ...    ...
495  Female  0.169492  0.936364      5
496  Female  0.745763  0.645455      4
497  Female  0.016949  0.781818      5
498    Male  0.169492  0.409091      5
499    Male  0.559322  0.736364      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.809353  0.587322      4
1      Male  0.926867  0.375390      2
2    Female  0.813400  0.581704      4
3    Female  0.884810  0.465951      3
4      Male  0.836314  0.548250      3
..      ...       ...       ...    ...
495  Female  0.178116  0.984010      5
496  Female  0.756127  0.654425      4
497  Female  0.021674  0.999765      5
498    Male  0.382762  0.923847      5
499    Male  0.604868  0.796326      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
scaler=MaxAbsScaler()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.809353  0.587322      4
1      Male  0.926867  0.375390      2
2    Female  0.813400  0.581704      4
3    Female  0.884810  0.465951      3
4      Male  0.836314  0.548250      3
..      ...       ...       ...    ...
495  Female  0.178116  0.984010      5
496  Female  0.756127  0.654425      4
497  Female  0.021674  0.999765      5
498    Male  0.382762  0.923847      5
499    Male  0.604868  0.796326      5

[500 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
df[['Height','Weight']]=scaler.fit_transform(df[['Height','Weight']])
df

     Gender    Height    Weight  Index
0      Male  0.230958 -0.274051      4
1      Male  0.505746 -0.773495      2
2    Female  0.240421 -0.287290      4
3    Female  0.407403 -0.560076      3
4      Male  0.294002 -0.366128      3
..      ...       ...       ...    ...
495  Female -1.245095  0.660788      5
496  Female  0.106496 -0.115916      4
497  Female -1.610911  0.697918      5
498    Male -0.766562  0.519009      5
499    Male -0.247201  0.218490      5

[500 rows x 4 columns]

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
data=pd.read_csv('/content/income(1) (1).csv',na_values=[" ?"])
data

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
0,45,Private,HS-grad,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,28,United-States,"less than or equal to 50,000"
1,24,Federal-gov,HS-grad,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"
2,44,Private,Some-college,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,"greater than 50,000"
3,27,Private,9th,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,"less than or equal to 50,000"
4,20,Private,Some-college,Never-married,Sales,Not-in-family,White,Male,0,0,35,United-States,"less than or equal to 50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,Local-gov,HS-grad,Never-married,Farming-fishing,Not-in-family,Black,Male,594,0,60,United-States,"less than or equal to 50,000"
31974,34,Local-gov,Some-college,Never-married,Protective-serv,Not-in-family,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31975,23,Private,Some-college,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,"less than or equal to 50,000"
31976,42,Local-gov,Some-college,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31977,29,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,"less than or equal to 50,000"

In [ ]:
data.isnull().sum()

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

In [ ]:
missing=data[data.isnull().any(axis=1)]
missing

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
8,17,NaN,11th,Never-married,NaN,Own-child,White,Female,0,0,5,United-States,"less than or equal to 50,000"
17,32,NaN,Some-college,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,United-States,"less than or equal to 50,000"
29,22,NaN,Some-college,Never-married,NaN,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"
42,52,NaN,12th,Never-married,NaN,Other-relative,Black,Male,594,0,40,United-States,"less than or equal to 50,000"
44,63,NaN,1st-4th,Married-civ-spouse,NaN,Husband,White,Male,0,0,35,United-States,"less than or equal to 50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31892,59,NaN,Bachelors,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,United-States,"greater than 50,000"
31934,20,NaN,HS-grad,Never-married,NaN,Other-relative,White,Female,0,0,35,United-States,"less than or equal to 50,000"
31945,28,NaN,Some-college,Married-civ-spouse,NaN,Wife,White,Female,0,1887,40,United-States,"greater than 50,000"
31967,80,NaN,HS-grad,Widowed,NaN,Not-in-family,White,Male,0,0,24,United-States,"less than or equal to 50,000"
31968,17,NaN,11th,Never-married,NaN,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"

In [ ]:
data2 = data.dropna(axis=0)
data2

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
0,45,Private,HS-grad,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,28,United-States,"less than or equal to 50,000"
1,24,Federal-gov,HS-grad,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,"less than or equal to 50,000"
2,44,Private,Some-college,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,"greater than 50,000"
3,27,Private,9th,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,"less than or equal to 50,000"
4,20,Private,Some-college,Never-married,Sales,Not-in-family,White,Male,0,0,35,United-States,"less than or equal to 50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,Local-gov,HS-grad,Never-married,Farming-fishing,Not-in-family,Black,Male,594,0,60,United-States,"less than or equal to 50,000"
31974,34,Local-gov,Some-college,Never-married,Protective-serv,Not-in-family,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31975,23,Private,Some-college,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,"less than or equal to 50,000"
31976,42,Local-gov,Some-college,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,"less than or equal to 50,000"
31977,29,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,"less than or equal to 50,000"

In [ ]:
sal=data['SalStat']
data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})
print(data2['SalStat'])

0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64

/tmp/ipykernel_443/2010331391.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})

In [ ]:
sal2=data2['SalStat']
dfs=pd.concat([sal,sal2],axis=1)
dfs

                             SalStat  SalStat
0       less than or equal to 50,000      0.0
1       less than or equal to 50,000      0.0
2                greater than 50,000      1.0
3       less than or equal to 50,000      0.0
4       less than or equal to 50,000      0.0
...                              ...      ...
31973   less than or equal to 50,000      0.0
31974   less than or equal to 50,000      0.0
31975   less than or equal to 50,000      0.0
31976   less than or equal to 50,000      0.0
31977   less than or equal to 50,000      0.0

[31978 rows x 2 columns]

In [ ]:
data2

,age,JobType,EdType,maritalstatus,occupation,relationship,race,gender,capitalgain,capitalloss,hoursperweek,nativecountry,SalStat
0,45,Private,HS-grad,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,28,United-States,0
1,24,Federal-gov,HS-grad,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,0
2,44,Private,Some-college,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,1
3,27,Private,9th,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,0
4,20,Private,Some-college,Never-married,Sales,Not-in-family,White,Male,0,0,35,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,Local-gov,HS-grad,Never-married,Farming-fishing,Not-in-family,Black,Male,594,0,60,United-States,0
31974,34,Local-gov,Some-college,Never-married,Protective-serv,Not-in-family,White,Female,0,0,40,United-States,0
31975,23,Private,Some-college,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,0
31976,42,Local-gov,Some-college,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,0
31977,29,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,0

In [ ]:
new_data=pd.get_dummies(data2, drop_first=True)
new_data

,age,capitalgain,capitalloss,hoursperweek,SalStat,JobType_ Local-gov,JobType_ Private,JobType_ Self-emp-inc,JobType_ Self-emp-not-inc,JobType_ State-gov,...,nativecountry_ Portugal,nativecountry_ Puerto-Rico,nativecountry_ Scotland,nativecountry_ South,nativecountry_ Taiwan,nativecountry_ Thailand,nativecountry_ Trinadad&Tobago,nativecountry_ United-States,nativecountry_ Vietnam,nativecountry_ Yugoslavia
0,45,0,0,28,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,24,0,0,40,0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,44,0,0,40,1,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,27,0,0,40,0,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,20,0,0,35,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,34,594,0,60,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31974,34,0,0,40,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31975,23,0,0,40,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31976,42,0,0,40,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31977,29,0,0,40,0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
columns_list=list(new_data.columns)

features=list(set(columns_list)-set(['SalStat']))
print(features)

y=new_data['SalStat'].values
print(y)

['JobType_ Without-pay', 'nativecountry_ Poland', 'race_ Other', 'EdType_ HS-grad', 'nativecountry_ Philippines', 'occupation_ Protective-serv', 'hoursperweek', 'occupation_ Prof-specialty', 'relationship_ Unmarried', 'JobType_ Local-gov', 'nativecountry_ Portugal', 'nativecountry_ Thailand', 'relationship_ Wife', 'EdType_ 7th-8th', 'EdType_ 11th', 'JobType_ State-gov', 'nativecountry_ Laos', 'nativecountry_ India', 'EdType_ Masters', 'nativecountry_ Dominican-Republic', 'nativecountry_ Greece', 'nativecountry_ China', 'nativecountry_ United-States', 'JobType_ Private', 'nativecountry_ Honduras', 'nativecountry_ Germany', 'JobType_ Self-emp-not-inc', 'nativecountry_ Hungary', 'nativecountry_ Hong', 'occupation_ Craft-repair', 'JobType_ Self-emp-inc', 'EdType_ 9th', 'EdType_ Prof-school', 'EdType_ Assoc-voc', 'nativecountry_ Japan', 'nativecountry_ El-Salvador', 'maritalstatus_ Married-AF-spouse', 'nativecountry_ Italy', 'occupation_ Exec-managerial', 'nativecountry_ Haiti', 'nativecountry_ Scotland', 'occupation_ Sales', 'EdType_ Some-college', 'relationship_ Not-in-family', 'occupation_ Armed-Forces', 'nativecountry_ Puerto-Rico', 'maritalstatus_ Widowed', 'EdType_ Doctorate', 'EdType_ Bachelors', 'race_ White', 'EdType_ Assoc-acdm', 'occupation_ Handlers-cleaners', 'nativecountry_ Guatemala', 'maritalstatus_ Never-married', 'nativecountry_ Cuba', 'occupation_ Machine-op-inspct', 'nativecountry_ Trinadad&Tobago', 'nativecountry_ Ecuador', 'nativecountry_ Yugoslavia', 'nativecountry_ Taiwan', 'occupation_ Transport-moving', 'EdType_ 5th-6th', 'EdType_ 12th', 'occupation_ Priv-house-serv', 'nativecountry_ Canada', 'race_ Asian-Pac-Islander', 'maritalstatus_ Separated', 'maritalstatus_ Married-civ-spouse', 'nativecountry_ France', 'nativecountry_ Nicaragua', 'nativecountry_ Mexico', 'occupation_ Tech-support', 'occupation_ Other-service', 'capitalgain', 'race_ Black', 'nativecountry_ Jamaica', 'age', 'nativecountry_ Vietnam', 'occupation_ Farming-fishing', 'nativecountry_ Ireland', 'EdType_ Preschool', 'nativecountry_ England', 'relationship_ Own-child', 'gender_ Male', 'nativecountry_ South', 'nativecountry_ Iran', 'nativecountry_ Peru', 'nativecountry_ Holand-Netherlands', 'maritalstatus_ Married-spouse-absent', 'capitalloss', 'relationship_ Other-relative', 'nativecountry_ Columbia', 'nativecountry_ Outlying-US(Guam-USVI-etc)', 'EdType_ 1st-4th']
[0 0 1 ... 0 0 0]

In [ ]:
x = new_data[features].values
print(x)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]

In [ ]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.3, random_state=0)
KNN_classifier=KNeighborsClassifier(n_neighbors = 5)
KNN_classifier.fit(train_x,train_y)

KNeighborsClassifier()

In [ ]:
prediction = KNN_classifier.predict(test_x)
confusionMmatrix = confusion_matrix(test_y, prediction)
print(confusionMmatrix)

[[6176  647]
 [ 808 1418]]

In [ ]:
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(test_y, prediction)
print(acc_score)

0.8392087523483258

In [ ]:
print('Misclassified samples: %d' % (test_y != prediction).sum())

Misclassified samples: 1455

In [ ]:
data.shape

(31978, 13)

# **FEATURE SELECTION TECHNIQUES**

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
import seaborn as sns
tips=sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
contingency_table=pd.crosstab(tips['sex'],tips['time'])
print(contingency_table)

time    Lunch  Dinner
sex
Male       33     124
Female     35      52

In [ ]:
chi2, p, _, _ = chi2_contingency(contingency_table)
print(f"Chi-Square Statistic: {chi2}")
print(f"P-value: {p}")

Chi-Square Statistic: 9.343808982970623
P-value: 0.002237400118075248

In [ ]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, mutual_info_classif, f_classif
data={
    'Feature1':[1,2,3,4,5],
    'Feature2': ['A','B','C','A','B'],
    'Feature3':[0,1,1,0,1],
    'Target' :[0,1,1,0,1]
}

df=pd.DataFrame(data)
X=df[['Feature1','Feature3']]
y=df['Target']

selector=SelectKBest(score_func=mutual_info_classif, k=1)
X_new = selector.fit_transform (X,y)
selected_feature_indices = selector.get_support(indices=True)
selected_features = X.columns[selected_feature_indices]
print("Selected Features:")
print(selected_features)

Selected Features:
Index(['Feature3'], dtype='object')

# **FEATURE SCALING**

In [ ]:
import pandas as pd
import numpy as np
import scipy as stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler, Normalizer, MaxAbsScaler, RobustScaler

# Load the BMI dataset
df = pd.read_csv('/content/bmi.csv')
display(df.head())

# Clean data
df = df.dropna()

# Calculate max absolute values
max_vals = np.max(np.abs(df[['Height','Weight']]))
print(f"Max Absolute Values:\n{max_vals}")

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

Max Absolute Values:
199

### Demonstrating Different Scaling Methods

In [ ]:
# Standard Scaler
sc = StandardScaler()
df_std = df.copy()
df_std[['Height','Weight']] = sc.fit_transform(df_std[['Height','Weight']])
print("Standard Scaler Result:")
display(df_std.head())

# Min-Max Scaler
mm_scaler = MinMaxScaler()
df_mm = df.copy()
df_mm[['Height','Weight']] = mm_scaler.fit_transform(df_mm[['Height','Weight']])
print("\nMin-Max Scaler Result:")
display(df_mm.head())

# Normalizer
norm_scaler = Normalizer()
df_norm = df.copy()
df_norm[['Height','Weight']] = norm_scaler.fit_transform(df_norm[['Height','Weight']])
print("\nNormalizer Result:")
display(df_norm.head())

# Max Absolute Scaler
ma_scaler = MaxAbsScaler()
df_ma = df.copy()
df_ma[['Height','Weight']] = ma_scaler.fit_transform(df_ma[['Height','Weight']])
print("\nMax Absolute Scaler Result:")
display(df_ma.head())

# Robust Scaler
rb_scaler = RobustScaler()
df_rb = df.copy()
df_rb[['Height','Weight']] = rb_scaler.fit_transform(df_rb[['Height','Weight']])
print("\nRobust Scaler Result:")
display(df_rb.head())

Standard Scaler Result:

   Gender    Height    Weight  Index
0    Male  0.247939 -0.309117      4
1    Male  1.164872 -0.587322      2
2  Female  0.920357  0.123647      4
3  Female  1.531645 -0.061823      3
4    Male -1.280283 -1.391027      3

Min-Max Scaler Result:

   Gender    Height    Weight  Index
0    Male  0.576271  0.418182      4
1    Male  0.830508  0.336364      2
2  Female  0.762712  0.545455      4
3  Female  0.932203  0.490909      3
4    Male  0.152542  0.100000      3

Normalizer Result:

   Gender    Height    Weight  Index
0    Male  0.875578  0.483077      4
1    Male  0.908381  0.418144      2
2  Female  0.859536  0.511075      4
3  Female  0.882353  0.470588      3
4    Male  0.925448  0.378875      3

Max Absolute Scaler Result:

   Gender    Height   Weight  Index
0    Male  0.874372  0.60000      4
1    Male  0.949749  0.54375      2
2  Female  0.929648  0.68750      4
3  Female  0.979899  0.65000      3
4    Male  0.748744  0.38125      3

Robust Scaler Result:

   Gender    Height    Weight  Index
0    Male  0.125000 -0.178571      4
1    Male  0.660714 -0.339286      2
2  Female  0.517857  0.071429      4
3  Female  0.875000 -0.035714      3
4    Male -0.767857 -0.803571      3

# **KNN CLASSIFICATION (Income Dataset)**

In [ ]:
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load and check the dataset
data = pd.read_csv('/content/income(1) (1).csv', na_values=[" ?"])
print("Missing values summary:")
print(data.isnull().sum())

# Drop missing values
data2 = data.dropna(axis=0)

# Map target variable (handling potential case sensitivity and mapping strings to integers)
data2['SalStat'] = data2['SalStat'].map({' less than or equal to 50,000': 0, ' greater than 50,000': 1})

# Convert categorical variables to dummy variables
new_data = pd.get_dummies(data2, drop_first=True)

# Prepare Features (X) and Target (y)
columns_list = list(new_data.columns)
features = list(set(columns_list) - set(['SalStat']))

X = new_data[features].values
y = new_data['SalStat'].values

# Split into training and testing sets
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=0)

# Train KNN Classifier
KNN_classifier = KNeighborsClassifier(n_neighbors=5)
KNN_classifier.fit(train_x, train_y)

# Predictions and Evaluation
prediction = KNN_classifier.predict(test_x)
cm = confusion_matrix(test_y, prediction)
acc = accuracy_score(test_y, prediction)

print("\nConfusion Matrix:")
print(cm)
print(f"\nAccuracy Score: {acc:.4f}")
print(f"Misclassified samples: {(test_y != prediction).sum()}")

Missing values summary:
age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

/tmp/ipykernel_443/972979125.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['SalStat'] = data2['SalStat'].map({' less than or equal to 50,000': 0, ' greater than 50,000': 1})

Confusion Matrix:
[[6176  647]
 [ 808 1418]]

Accuracy Score: 0.8392
Misclassified samples: 1455

# **FEATURE SELECTION TECHNIQUES**

In [ ]:
from scipy.stats import chi2_contingency

# Chi-Square Test using Tips dataset
tips = sns.load_dataset('tips')
contingency_table = pd.crosstab(tips['sex'], tips['time'])
print("Contingency Table:")
print(contingency_table)

chi2, p, _, _ = chi2_contingency(contingency_table)
print(f"\nChi-Square Statistic: {chi2:.4f}")
print(f"P-value: {p:.4f}")

Contingency Table:
time    Lunch  Dinner
sex
Male       33     124
Female     35      52

Chi-Square Statistic: 9.3438
P-value: 0.0022

In [ ]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif

# SelectKBest with Mutual Information on synthetic data
synthetic_data = {
    'Feature1': [1, 2, 3, 4, 5],
    'Feature2': ['A', 'B', 'C', 'A', 'B'],
    'Feature3': [0, 1, 1, 0, 1],
    'Target': [0, 1, 1, 0, 1]
}

df_syn = pd.DataFrame(synthetic_data)
X_syn = df_syn[['Feature1', 'Feature3']]
y_syn = df_syn['Target']

selector = SelectKBest(score_func=mutual_info_classif, k=1)
X_new = selector.fit_transform(X_syn, y_syn)
selected_indices = selector.get_support(indices=True)

print("Selected Features:")
print(X_syn.columns[selected_indices])

Selected Features:
Index(['Feature3'], dtype='object')